modLoader = "javafml"
loaderVersion = "*"
license = "${mod_license}"

[[mods]]
modId = "testmod"
version = "${mod_version}"
displayName = "Test Mod"
authors = "${mod_author}"
description = "Testing environment for mod development and testing purposes"
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.testmod]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"