modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"
license = "GPL-3"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''
${modDescription}
'''
logoFile = "assets/${modId}/icon.png"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "${neoForgeCompatibleVersions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${modId}-common.mixins.json"
[[mixins]]
config = "${modId}.mixins.json"